### ISSUE TITLE
how to bloom new release?

### ISSUE THREAD

**Issue by flixr** [ros2-gbp/rc_genicam_api-release#1]
@cottsay seems this repo was automatically generated from rolling?
Should this repo still be used for galactic, or rather https://github.com/roboception-gbp/rc_genicam_api-release ?

How can I now bloom a new release into galactic?

It worked for foxy and rolling:
https://github.com/ros/rosdistro/pull/30384
https://github.com/ros/rosdistro/pull/30383

**Comment by cottsay** [comment]
Hi, @flixr. Indeed packages in rolling that have release repositories outside of ros2-gbp get forked into ros2-gbp as part of a new rosdistro branching from rolling. You have three choices:
1. Move your release repo into ros2-gbp for future releases
2. Override the fork here and redirect `galactic` to the repo in `roboception-gbp`, and play the same game again when humble forks from rolling
3. Drop your package from rolling

Tagging @nuclearsandwich to keep me honest.

**Comment by flixr** [comment]
Can you elaborate on option 3? Why would dropping the package from rolling now affect galactic?

How would I release into this repo? Request write access to it?
I would need to do this for every package that I had in rolling?

How do you guys expect people to handle this, i.e. what is the recommend workflow?
Should then everyone release into ros2-gbp?
Or update the rosdistro to point to the same as rolling again?

**Comment by cottsay** [comment]
> Can you elaborate on option 3?

This was an incomplete thought, I apologize. It is part of the Rolling automation that when a new release happens, it branches from Rolling and any release repositories outside of `ros2-gbp` are forked into `ros2-gbp`. If you don't want your release repository to be forked like this, the only other option is to move your release repository to `ros2-gbp`.

> How would I release into this repo? Request write access to it?

Yeah, we can give you access to it and you can make your future releases there. That's probably the best way to solve the problem.

**Comment by flixr** [comment]
This essentially means that over time most repos will move into ros2-gbp and some of you need to manage access to all of them.
Which also means that it would probably make more sense to create a release repo in ros2-gbp from the beginning?

How did other people/teams handle this, I can't be the first one to run into this?

Please don't get me wrong, I really appreciate the effort you guys put in! And it's nice that the package automatically ended up in galactic.
I just doesn't strike me as the best/scalable approach if you then need to take care of this for every release repo...

**Comment by nuclearsandwich** [comment]
> This essentially means that over time most repos will move into ros2-gbp and some of you need to manage access to all of them.
> Which also means that it would probably make more sense to create a release repo in ros2-gbp from the beginning?
> 
> How did other people/teams handle this, I can't be the first one to run into this?

You're not the first but in the grand scheme of things it's a relatively new problem since ros2-gbp only became the required home for ROS 2 release repositories with the launch of the Rolling distribution, and until recently we've been handling it in a very ad-hoc and post-hoc basis, reaching out to specific maintainers or waiting for maintainers to contact us when making new releases into distributions created with the rolling tools.

That's beginning to change with the [transition announced here](https://discourse.ros.org/t/upcoming-changes-to-ros2-gbp-organization/21878) which will bring a more organized and consistent pattern to the ros2-gbp permissions model and, in time, I hope we can make requesting access to, and requesting new release repositories part of the standard bring-up process for new maintainers or bake it directly into the release process so that these things are automatically created when running our release tools.

**Comment by flixr** [comment]
Ok, thanks a lot for your hard work guys!
